# Generated by Django 4.2.4 on 2023-09-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_tag_scope_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Принадлежность', 'verbose_name_plural': 'Принадлежность'},
        ),
    ]
